### ISSUE TITLE
allow `cutoff` configuration

### ISSUE THREAD

**Issue by VinSpee** [ForbesLindesay/dehumanize-date#4]
Hi,

I ran into an issue with [cutoff](https://github.com/ForbesLindesay/dehumanize-date/blob/master/index.js#L101) - when a use enters `5/25/76`, the dehumanized value of year becomes `2076`, rather than `1976`, which is what the user anticipates.

**Comment by ForbesLindesay** [comment]
I would accept a pull requrest that changes https://github.com/ForbesLindesay/dehumanize-date/blob/master/index.js#L27 to take an `options` object with properties for `usa`, `cutoff` and `now` (all with the current defaults).  If `typeof options !== 'object'` it should assume that `options = {usa: options}` for backwards compatibility.
