### ISSUE TITLE
Allow any prefix of month, not just first 3 characters. 

### ISSUE THREAD

**Issue by clord** [ForbesLindesay/dehumanize-date#6]
It would be nice to allow more or less characters to be used as short months. The library might accept the _least unique prefix_ for any given month, and only validate any additional characters (perhaps accepting spelling mistakes under an option?)

For instance, I can't help but type `Sept 1, 2015`, but that extra `t` causes parse to fail as is. Also, since September is the only month that starts with S, the tool could determine that `Se 1, 2015` is the same date, for example. 

would be glad to prepare a pull request for this once some discussion on design is complete.

I personally prefer a statically constructed trie that maps to unique month numbers, and then an optional 'affix validator' that checks any additional provided characters are correct after the unique prefix.

**Comment by ForbesLindesay** [comment]
I agree, this would be good.  I'm happy to accept a pull request.

**Comment by JeromeFitz** [comment]
Happy to give this a whirl RE: [Twitter](https://twitter.com/ForbesLindesay/status/758231156936609792)
