### ISSUE TITLE
short weekday names

### ISSUE THREAD

**Issue by offsky** [ForbesLindesay/dehumanize-date#9]
Could we please have support for "next/last mo/mon/tu/tue/we/wed...."? This would be very convenient.

**Comment by ForbesLindesay** [comment]
Happy to accept a pull request.

**Comment by JeromeFitz** [comment]
Happy to give this a whirl RE: [Twitter](https://twitter.com/ForbesLindesay/status/758231156936609792)

**Comment by JeromeFitz** [comment]
I'll port the code over from #10, to work for short weekday names.

**Comment by ForbesLindesay** [comment]
#12 seems to have resolved this.
